export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";

export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_PENDING";

export const VIEW_PROFILE = "VIEW_PROFILE";

export const CHANGE_ACTIVE_PAGE = "CHANGE_ACTIVE_PAGE";
